name: neru
description: "Psicologia del Deporte."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  intl: ^0.18.1
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3
  audioplayers: ^6.5.0
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pdf/neru.pdf
    - assets/audio/muscular.mp3
    - assets/variables/
    - .env
  fonts:
    - family: Monserrat
      fonts:
      - asset: assets/fonts/Montserrat-Regular.otf
      - asset: assets/fonts/Montserrat-Bold.otf
        weight: 700
  
flutter_native_splash:
  color: "#302F40"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    icon_background_color: "#302F40"

